### ISSUE TITLE
chan_echolink: Build failure caused by commit a2bc08c5d7ba24922bddd6a39beef9ecf7638e20

### ISSUE THREAD

**Issue by InterLinked1** [AllStarLink/app_rpt#504]
Commit a2bc08c5d7ba24922bddd6a39beef9ecf7638e20 seems like it doesn't build properly: https://github.com/AllStarLink/app_rpt/actions/runs/13460791178/job/37615359598

Strange because the PR build seemed to succeed but it failed once merged: https://github.com/AllStarLink/app_rpt/pull/432

```
   [CC] chan_usbradio.c -> chan_usbradio.o
chan_echolink.c:232:25: error: expected identifier or '(' before '+' token
  232 |                         + 16 \ /* ASL & EL nodes #'s */
      |                         ^
chan_echolink.c:232:30: error: stray '\' in program
  232 |                         + 16 \ /* ASL & EL nodes #'s */
      |                              ^
chan_echolink.c:233:30: error: stray '\' in program
  233 |                         + 80 \ /* room for "a" message */
      |                              ^
chan_echolink.c:558:24: error: 'tdesc' undeclared here (not in a function)
  558 |         .description = tdesc,
      |                        ^~~~~
chan_echolink.c: In function 'send_info':
chan_echolink.c:1928:29: error: passing argument 1 of 'ast_str_set' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1928 |                 ast_str_set(pkt, 0, EL_WELCOME_MESSAGE, instp->astnode, instp->mycall, instp->mynode);
      |                             ^~~
      |                             |
      |                             struct ast_str *
In file included from /usr/src/asterisk-22.2.0/include/asterisk/lock.h:669,
                 from /usr/src/asterisk-22.2.0/include/asterisk/utils.h:32,
                 from /usr/src/asterisk-22.2.0/include/asterisk/alertpipe.h:22,
                 from /usr/src/asterisk-22.2.0/include/asterisk/channel.h:125,
                 from chan_echolink.c:178:
/usr/src/asterisk-22.2.0/include/asterisk/strings.h:1102:26: note: expected 'struct ast_str **' but argument is of type 'struct ast_str *'
 1102 |         struct ast_str **buf, ssize_t max_len, const char *fmt, ...),
      |         ~~~~~~~~~~~~~~~~~^~~
/usr/src/asterisk-22.2.0/include/asterisk/inline_api.h:52:61: note: in definition of macro 'AST_INLINE_API'
   52 | #define AST_INLINE_API(hdr, body) static hdr; static inline hdr body
      |                                                             ^~~
chan_echolink.c:1931:40: error: passing argument 1 of 'ast_str_append' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1931 |                         ast_str_append(pkt, 0, "%s\n\n", instp->mymessage);
      |                                        ^~~
      |                                        |
      |                                        struct ast_str *
/usr/src/asterisk-22.2.0/include/asterisk/strings.h:1128:26: note: expected 'struct ast_str **' but argument is of type 'struct ast_str *'
 1128 |         struct ast_str **buf, ssize_t max_len, const char *fmt, ...),
      |         ~~~~~~~~~~~~~~~~~^~~
/usr/src/asterisk-22.2.0/include/asterisk/inline_api.h:52:61: note: in definition of macro 'AST_INLINE_API'
   52 | #define AST_INLINE_API(hdr, body) static hdr; static inline hdr body
      |                                                             ^~~
chan_echolink.c:1934:21: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
 1934 |                 if (cp = (*(struct el_node **) nodep)->pvt ? (*(struct el_node **) nodep)->pvt->linkstr : NULL) {
      |                     ^~
chan_echolink.c:1935:40: error: passing argument 1 of 'ast_str_append' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1935 |                         ast_str_append(pkt, 0, "Systems Linked:\r%s", cp);
      |                                        ^~~
      |                                        |
      |                                        struct ast_str *
/usr/src/asterisk-22.2.0/include/asterisk/strings.h:1128:26: note: expected 'struct ast_str **' but argument is of type 'struct ast_str *'
 1128 |         struct ast_str **buf, ssize_t max_len, const char *fmt, ...),
      |         ~~~~~~~~~~~~~~~~~^~~
/usr/src/asterisk-22.2.0/include/asterisk/inline_api.h:52:61: note: in definition of macro 'AST_INLINE_API'
   52 | #define AST_INLINE_API(hdr, body) static hdr; static inline hdr body
      |                                                             ^~~
chan_echolink.c:1938:64: error: implicit declaration of function 'ast_str_len'; did you mean 'ast_str_set'? [-Werror=implicit-function-declaration]
 1938 |                 sendto(instp->audio_sock, ast_str_buffer(pkt), ast_str_len(pkt), 0, (struct sockaddr *) &sin, sizeof(sin));
      |                                                                ^~~~~~~~~~~
      |                                                                ast_str_set
cc1: all warnings being treated as errors
make[1]: *** [/usr/src/asterisk-22.2.0/Makefile.rules:164: chan_echolink.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:396: channels] Error 2
Error: Process completed with exit code 1.
```

**Comment by mkmer** [comment]
https://github.com/AllStarLink/app_rpt/pull/505
